name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: learn-finnish-app/package-lock.json

      # 3. Install and build
      - name: Install dependencies and build
        working-directory: learn-finnish-app
        run: |
          npm install
          npm run build

      # 4. Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "learn-finnish-app"   # where package.json is
          api_location: ""                    # no backend
          output_location: "build"            # build output folder
